export const filterOptions = {
  product_types: [
    "Плитка",
    "Керамогранит",
    "Мозаика",
    "Ступень",
    "Плинтус",
    "Вставка",
  ],
  colors: [
    "белый",
    "бежевый",
    "серый",
    "светло-серый",
    "темно-серый",
    "коричневый",
    "голубой",
    "черный",
    "многоцветный",
    "золотистый",
    "песочный",
    "темно-бежевый",
    "светло-бежевый",
    "темно-коричневый",
    "светло-коричневый",
    "синий",
  ],
  dimensions: [
    "7x60",
    "18x60",
    "18.5x59.8",
    "22x90",
    "28x25",
    "30x30",
    "30x60",
    "42x42",
    "45x90",
    "60x60",
    "60x120",
  ],
  designs: [
    "Дерево",
    "Камень",
    "Мрамор",
    "Бетон",
    "Однотонный",
    "Геометрия",
  ],
  surface_types: [
    "матовая",
    "полированная (глянец)",
    "сатиновая",
  ],
  surfaces: [
    "Глянцевая",
    "Матовая",
    "Полированная",
    "Сатинированная",
    "Структурная",
    "Рельефная",
    "Лаппатированная",
  ],
  applications: [
    "Стена",
    "Пол",
    "Пол и стена",
    "Ступень",
    "Декор",
  ],
  price_range: {
    min: 400,
    max: 9500,
  },

  // Design category mapping to collections
  designCategoryMapping: {
    "Дерево": ["Lofthouse", "Woodhouse", "Wood Concept Natural", "Wood Concept Prime", "Wood Concept Rustic", "Chesterwood", "Finwood", "Maplewood", "Northwood", "Patinawood", "Sandwood", "Starwood", "Antiquewood", "Colorwood", "Harbourwood", "Timber Land", "Kauri Wood", "Bonsai Tree", "Teakwood", "Amberwood", "Oakwood", "Fregat", "Montioni"],
    "Камень": ["Royal Stone", "Royal stone", "Slate", "Mont Blanc", "Deco", "Calacatta", "Deep Calacatta", "Classy Marble", "Gold Venice", "Soft Concrete", "Silver Roots", "Grigio Nuovalato", "Lumina Onyx", "Granite", "Dako", "Desert", "Stonehouse", "Limestone", "Sandstone"],
    "Мрамор": ["Calacatta", "Deep Calacatta", "Lumina Onyx", "Classy Marble", "Gold Venice", "Carrara", "Empire"],
    "Бетон": ["Soft Concrete", "Effecta", "Landscape", "Concretehouse", "Dako", "Loft"],
    "Однотонный": ["Loft", "Navi", "Pudra", "Queen", "Raven", "Sonata", "Моноколор"],
    "Геометрия": ["Atria", "Coliseum", "Galaxy", "Infinity", "Lorenzo", "Mercury", "Orion", "Polaris", "Space", "Greenhouse", "Blend", "Oriental", "Palitra", "Sevilla", "Siena", "Tiffany", "Daisy", "Exterio", "JackStone", "Cambio", "Rustico", "Silvia", "Stilo", "Lina", "Marina", "Inverno", "Cento", "Manzolino", "Vena", "Nero", "Pacific", "Pamir", "Sherbrooke", "Asher", "Ultra", "Spark", "Modis", "Residence", "Stonehouse", "Desert", "Limestone", "Coastline", "Sandstone", "Stellar", "Luna", "Magic", "Ritmo", "Avalon", "Stream", "Motley", "Carpet", "Конфетти"],
  },
}
