export interface Product {
  id: number
  sku: string
  name: string
  slug: string
  brand: string
  collection: string
  product_type: string
  format: string
  surface: string
  color: string
  material_type: string
  application: string
  rooms: string[]
  thickness: string
  pieces_per_box: number
  sqm_per_box: number
  country: string
  price_retail: number
  price_official: number | null
  currency: string
  stock_yanino: number
  stock_factory: number
  description: string
  images: string[]
  main_image: string
  is_new: boolean
  is_bestseller: boolean
  is_discount: boolean
  rating: number
  reviews_count: number
}

export interface Category {
  id: number
  name: string
  slug: string
  image: string
  count: number
}

export interface Collection {
  id: number
  name: string
  slug: string
  image: string
  product_count: number
}

export const categories: Category[] = [
  { id: 1, name: "Керамическая плитка", slug: "keramicheskaya-plitka", image: "/images/categories/ceramic.jpg", count: 342 },
  { id: 2, name: "Керамогранит", slug: "keramogranit", image: "/images/categories/porcelain.jpg", count: 256 },
  { id: 3, name: "Мозаика", slug: "mozaika", image: "/images/categories/mosaic.jpg", count: 89 },
  { id: 4, name: "Ступени", slug: "stupeni", image: "/images/categories/steps.jpg", count: 64 },
]

export const collections: Collection[] = [
  { id: 1, name: "Marble Charm", slug: "marble-charm", image: "/images/tiles/marble-white.jpg", product_count: 6 },
  { id: 2, name: "Wood Concept", slug: "wood-concept", image: "/images/tiles/wood-beige.jpg", product_count: 5 },
  { id: 3, name: "Loft Brick", slug: "loft-brick", image: "/images/tiles/gray-concrete.jpg", product_count: 4 },
  { id: 4, name: "Mediterranean", slug: "mediterranean", image: "/images/tiles/mosaic-blue.jpg", product_count: 3 },
  { id: 5, name: "Dark Elegance", slug: "dark-elegance", image: "/images/tiles/black-stone.jpg", product_count: 4 },
  { id: 6, name: "Terrazzo Art", slug: "terrazzo-art", image: "/images/tiles/terrazzo-light.jpg", product_count: 3 },
  { id: 7, name: "Onyx Royal", slug: "onyx-royal", image: "/images/tiles/onyx-cream.jpg", product_count: 3 },
  { id: 8, name: "Sandstone", slug: "sandstone", image: "/images/tiles/sandstone-beige.jpg", product_count: 3 },
]

export const products: Product[] = [
  // ===== MARBLE CHARM =====
  {
    id: 1,
    sku: "C-WG4H092D",
    name: "Marble Charm Белый 29.7x60",
    slug: "marble-charm-belyj-297x60",
    brand: "Cersanit",
    collection: "Marble Charm",
    product_type: "Керамическая плитка",
    format: "29.7x60",
    surface: "Глянцевая",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная", "Кухня"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1290,
    price_official: 1490,
    currency: "RUB",
    stock_yanino: 450,
    stock_factory: 1200,
    description: "Керамическая настенная плитка из коллекции Marble Charm с изысканным мраморным дизайном. Глянцевая поверхность создает элегантный интерьер ванной комнаты или кухни. Каждая плитка имеет уникальный рисунок прожилок, имитирующий натуральный мрамор Calacatta.",
    images: ["/images/tiles/marble-white.jpg", "/images/tiles/marble-beige.jpg", "/images/tiles/marble-white.jpg"],
    main_image: "/images/tiles/marble-white.jpg",
    is_new: true,
    is_bestseller: true,
    is_discount: false,
    rating: 4.8,
    reviews_count: 23,
  },
  {
    id: 2,
    sku: "C-WG4H093D",
    name: "Marble Charm Серый 29.7x60",
    slug: "marble-charm-seryj-297x60",
    brand: "Cersanit",
    collection: "Marble Charm",
    product_type: "Керамическая плитка",
    format: "29.7x60",
    surface: "Глянцевая",
    color: "Серый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1350,
    price_official: null,
    currency: "RUB",
    stock_yanino: 320,
    stock_factory: 900,
    description: "Настенная керамическая плитка с мраморным рисунком в серых тонах. Глянцевая поверхность идеально подходит для стен ванной комнаты. Серые прожилки на светлом фоне создают спокойную атмосферу.",
    images: ["/images/tiles/marble-white.jpg", "/images/tiles/marble-beige.jpg"],
    main_image: "/images/tiles/marble-white.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.5,
    reviews_count: 12,
  },
  {
    id: 3,
    sku: "C-WG4H094D",
    name: "Marble Charm Бежевый 29.7x60",
    slug: "marble-charm-bezhevyj-297x60",
    brand: "Cersanit",
    collection: "Marble Charm",
    product_type: "Керамическая плитка",
    format: "29.7x60",
    surface: "Глянцевая",
    color: "Бежевый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная", "Кухня"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1310,
    price_official: 1490,
    currency: "RUB",
    stock_yanino: 280,
    stock_factory: 750,
    description: "Настенная плитка из коллекции Marble Charm в теплых бежевых тонах. Имитация натурального мрамора с золотистыми прожилками. Идеально сочетается с белой и серой плиткой этой же коллекции.",
    images: ["/images/tiles/marble-beige.jpg", "/images/tiles/marble-white.jpg"],
    main_image: "/images/tiles/marble-beige.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: true,
    rating: 4.7,
    reviews_count: 18,
  },
  {
    id: 4,
    sku: "C-PG4H095D",
    name: "Marble Charm Белый 60x60",
    slug: "marble-charm-belyj-60x60",
    brand: "Cersanit",
    collection: "Marble Charm",
    product_type: "Керамогранит",
    format: "60x60",
    surface: "Полированная",
    color: "Белый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная", "Гостиная", "Холл"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 2190,
    price_official: 2490,
    currency: "RUB",
    stock_yanino: 180,
    stock_factory: 600,
    description: "Крупноформатный полированный керамогранит с мраморным дизайном. Зеркальный блеск и реалистичные прожилки создают роскошный интерьер. Подходит для пола в ванной, гостиной и холле.",
    images: ["/images/tiles/marble-white.jpg", "/images/tiles/marble-beige.jpg"],
    main_image: "/images/tiles/marble-white.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.9,
    reviews_count: 7,
  },
  {
    id: 5,
    sku: "C-PG4H096D",
    name: "Marble Charm Серый 60x120",
    slug: "marble-charm-seryj-60x120",
    brand: "Cersanit",
    collection: "Marble Charm",
    product_type: "Керамогранит",
    format: "60x120",
    surface: "Полированная",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Холл"],
    thickness: "10 мм",
    pieces_per_box: 2,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 2890,
    price_official: null,
    currency: "RUB",
    stock_yanino: 90,
    stock_factory: 350,
    description: "Премиальный крупноформатный керамогранит 60x120 с полированной поверхностью. Минимум швов, максимум стиля. Идеален для больших пространств.",
    images: ["/images/tiles/marble-white.jpg"],
    main_image: "/images/tiles/marble-white.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.8,
    reviews_count: 4,
  },
  {
    id: 6,
    sku: "C-MZ4H097D",
    name: "Marble Charm Мозаика Белый 30x30",
    slug: "marble-charm-mozaika-belyj-30x30",
    brand: "Cersanit",
    collection: "Marble Charm",
    product_type: "Мозаика",
    format: "30x30",
    surface: "Глянцевая",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная"],
    thickness: "8 мм",
    pieces_per_box: 12,
    sqm_per_box: 1.08,
    country: "Россия",
    price_retail: 1890,
    price_official: null,
    currency: "RUB",
    stock_yanino: 150,
    stock_factory: 400,
    description: "Мозаика из коллекции Marble Charm на сетке. Белый мрамор в мозаичном исполнении -- идеальный акцент для ванной комнаты.",
    images: ["/images/tiles/mosaic-white.jpg", "/images/tiles/marble-white.jpg"],
    main_image: "/images/tiles/mosaic-white.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.6,
    reviews_count: 9,
  },

  // ===== WOOD CONCEPT =====
  {
    id: 7,
    sku: "C-WF4P093D",
    name: "Wood Concept Natural Бежевый 22x90",
    slug: "wood-concept-natural-bezhevyj-22x90",
    brand: "Cersanit",
    collection: "Wood Concept",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "Матовая",
    color: "Бежевый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Спальня", "Кухня"],
    thickness: "10 мм",
    pieces_per_box: 7,
    sqm_per_box: 1.39,
    country: "Россия",
    price_retail: 1850,
    price_official: null,
    currency: "RUB",
    stock_yanino: 280,
    stock_factory: 800,
    description: "Керамогранит под дерево из коллекции Wood Concept Natural. Реалистичная текстура натурального дуба, матовая поверхность. Идеально подходит для пола в гостиной и спальне. 6 уникальных график создают естественный рисунок укладки.",
    images: ["/images/tiles/wood-beige.jpg", "/images/tiles/wood-dark.jpg"],
    main_image: "/images/tiles/wood-beige.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.9,
    reviews_count: 41,
  },
  {
    id: 8,
    sku: "C-WC4H111D",
    name: "Wood Concept Rustic Коричневый 18.5x60",
    slug: "wood-concept-rustic-korichnevyj-185x60",
    brand: "Cersanit",
    collection: "Wood Concept",
    product_type: "Керамогранит",
    format: "18.5x60",
    surface: "Матовая",
    color: "Коричневый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Кухня", "Прихожая"],
    thickness: "10 мм",
    pieces_per_box: 9,
    sqm_per_box: 1.0,
    country: "Россия",
    price_retail: 1590,
    price_official: 1790,
    currency: "RUB",
    stock_yanino: 200,
    stock_factory: 650,
    description: "Керамогранит под дерево с рустикальной текстурой. Тёплые коричневые тона создают уютную атмосферу. Выраженный древесный рисунок с сучками и трещинками.",
    images: ["/images/tiles/wood-dark.jpg", "/images/tiles/wood-beige.jpg"],
    main_image: "/images/tiles/wood-dark.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.7,
    reviews_count: 19,
  },
  {
    id: 9,
    sku: "C-WC4H112D",
    name: "Wood Concept Classic Светлый 20x120",
    slug: "wood-concept-classic-svetlyj-20x120",
    brand: "Cersanit",
    collection: "Wood Concept",
    product_type: "Керамогранит",
    format: "20x120",
    surface: "Матовая",
    color: "Бежевый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Спальня"],
    thickness: "10 мм",
    pieces_per_box: 5,
    sqm_per_box: 1.2,
    country: "Россия",
    price_retail: 2150,
    price_official: null,
    currency: "RUB",
    stock_yanino: 150,
    stock_factory: 500,
    description: "Крупноформатный керамогранит под дерево. Длинная доска 120 см для максимально реалистичной имитации паркета. Светлый дуб с деликатной текстурой.",
    images: ["/images/tiles/wood-beige.jpg"],
    main_image: "/images/tiles/wood-beige.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.8,
    reviews_count: 11,
  },
  {
    id: 10,
    sku: "C-WC4H113D",
    name: "Wood Concept Wenge Тёмный 22x90",
    slug: "wood-concept-wenge-temnyj-22x90",
    brand: "Cersanit",
    collection: "Wood Concept",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "Матовая",
    color: "Коричневый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Кабинет"],
    thickness: "10 мм",
    pieces_per_box: 7,
    sqm_per_box: 1.39,
    country: "Россия",
    price_retail: 1950,
    price_official: 2190,
    currency: "RUB",
    stock_yanino: 110,
    stock_factory: 400,
    description: "Керамогранит с имитацией тёмного дерева венге. Глубокий шоколадный оттенок с тонкими светлыми прожилками. Создает контрастный и стильный пол.",
    images: ["/images/tiles/wood-dark.jpg"],
    main_image: "/images/tiles/wood-dark.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: true,
    rating: 4.6,
    reviews_count: 27,
  },
  {
    id: 11,
    sku: "C-WC4H114D",
    name: "Wood Concept Grey Серый 22x90",
    slug: "wood-concept-grey-seryj-22x90",
    brand: "Cersanit",
    collection: "Wood Concept",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "Матовая",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Спальня", "Прихожая"],
    thickness: "10 мм",
    pieces_per_box: 7,
    sqm_per_box: 1.39,
    country: "Россия",
    price_retail: 1850,
    price_official: null,
    currency: "RUB",
    stock_yanino: 220,
    stock_factory: 700,
    description: "Керамогранит под дерево в модном сером оттенке. Выбеленный дуб -- один из самых популярных трендов. Нейтральный цвет подходит к любому интерьеру.",
    images: ["/images/tiles/wood-beige.jpg"],
    main_image: "/images/tiles/wood-beige.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.7,
    reviews_count: 15,
  },

  // ===== LOFT BRICK =====
  {
    id: 12,
    sku: "C-GR4S061D",
    name: "Loft Brick Серый 60x60",
    slug: "loft-brick-seryj-60x60",
    brand: "Cersanit",
    collection: "Loft Brick",
    product_type: "Керамогранит",
    format: "60x60",
    surface: "Матовая",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Прихожая"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 1650,
    price_official: 1890,
    currency: "RUB",
    stock_yanino: 120,
    stock_factory: 600,
    description: "Керамогранит в стиле лофт с текстурой бетона. Матовая поверхность с противоскользящими свойствами. Крупный формат 60x60 визуально расширяет пространство.",
    images: ["/images/tiles/gray-concrete.jpg", "/images/tiles/cement-light.jpg"],
    main_image: "/images/tiles/gray-concrete.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: true,
    rating: 4.6,
    reviews_count: 15,
  },
  {
    id: 13,
    sku: "C-GR4S062D",
    name: "Loft Brick Светло-серый 60x60",
    slug: "loft-brick-svetlo-seryj-60x60",
    brand: "Cersanit",
    collection: "Loft Brick",
    product_type: "Керамогранит",
    format: "60x60",
    surface: "Матовая",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Кухня", "Прихожая"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 1650,
    price_official: null,
    currency: "RUB",
    stock_yanino: 180,
    stock_factory: 550,
    description: "Светлый бетонный керамогранит из коллекции Loft Brick. Нейтральный серый тон отлично подходит для скандинавских интерьеров и стиля минимализм.",
    images: ["/images/tiles/cement-light.jpg", "/images/tiles/gray-concrete.jpg"],
    main_image: "/images/tiles/cement-light.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.7,
    reviews_count: 22,
  },
  {
    id: 14,
    sku: "C-GR4S063D",
    name: "Loft Brick Антрацит 30x60",
    slug: "loft-brick-antracit-30x60",
    brand: "Cersanit",
    collection: "Loft Brick",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "Матовая",
    color: "Чёрный",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Прихожая", "Кухня"],
    thickness: "10 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 1750,
    price_official: null,
    currency: "RUB",
    stock_yanino: 95,
    stock_factory: 380,
    description: "Тёмный керамогранит в стиле бетона с антрацитовым оттенком. Брутальный индустриальный характер для смелых интерьерных решений.",
    images: ["/images/tiles/slate-dark.jpg", "/images/tiles/gray-concrete.jpg"],
    main_image: "/images/tiles/slate-dark.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.5,
    reviews_count: 8,
  },
  {
    id: 15,
    sku: "C-WL4S064D",
    name: "Loft Brick Настенная Белый 25x75",
    slug: "loft-brick-nastennaya-belyj-25x75",
    brand: "Cersanit",
    collection: "Loft Brick",
    product_type: "Керамическая плитка",
    format: "25x75",
    surface: "Матовая",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная", "Кухня"],
    thickness: "9 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.5,
    country: "Россия",
    price_retail: 1190,
    price_official: 1390,
    currency: "RUB",
    stock_yanino: 350,
    stock_factory: 900,
    description: "Настенная плитка с текстурой бетона в белом цвете. Матовая поверхность для стен в стиле минимализм. Отлично сочетается с напольным керамогранитом Loft Brick.",
    images: ["/images/tiles/cement-light.jpg"],
    main_image: "/images/tiles/cement-light.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: true,
    rating: 4.4,
    reviews_count: 13,
  },

  // ===== MEDITERRANEAN =====
  {
    id: 16,
    sku: "C-MZ2M044D",
    name: "Mediterranean Мозаика Голубой 30x30",
    slug: "mediterranean-mozaika-goluboj-30x30",
    brand: "Cersanit",
    collection: "Mediterranean",
    product_type: "Мозаика",
    format: "30x30",
    surface: "Глянцевая",
    color: "Голубой",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная", "Бассейн"],
    thickness: "8 мм",
    pieces_per_box: 12,
    sqm_per_box: 1.08,
    country: "Россия",
    price_retail: 2100,
    price_official: null,
    currency: "RUB",
    stock_yanino: 95,
    stock_factory: 300,
    description: "Мозаика в средиземноморском стиле. Голубые оттенки создают атмосферу морского побережья. Идеально подходит для ванных комнат и бассейнов.",
    images: ["/images/tiles/mosaic-blue.jpg", "/images/tiles/mosaic-white.jpg"],
    main_image: "/images/tiles/mosaic-blue.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.7,
    reviews_count: 8,
  },
  {
    id: 17,
    sku: "C-MZ2M045D",
    name: "Mediterranean Мозаика Белый 30x30",
    slug: "mediterranean-mozaika-belyj-30x30",
    brand: "Cersanit",
    collection: "Mediterranean",
    product_type: "Мозаика",
    format: "30x30",
    surface: "Глянцевая",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная", "Кухня"],
    thickness: "8 мм",
    pieces_per_box: 12,
    sqm_per_box: 1.08,
    country: "Россия",
    price_retail: 1950,
    price_official: null,
    currency: "RUB",
    stock_yanino: 130,
    stock_factory: 350,
    description: "Белая мозаика из коллекции Mediterranean. Классический белый цвет в мозаичном исполнении -- универсальное решение для любого интерьера.",
    images: ["/images/tiles/mosaic-white.jpg"],
    main_image: "/images/tiles/mosaic-white.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.8,
    reviews_count: 14,
  },
  {
    id: 18,
    sku: "C-WL2M046D",
    name: "Mediterranean Настенная Голубой 25x75",
    slug: "mediterranean-nastennaya-goluboj-25x75",
    brand: "Cersanit",
    collection: "Mediterranean",
    product_type: "Керамическая плитка",
    format: "25x75",
    surface: "Глянцевая",
    color: "Голубой",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная"],
    thickness: "9 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.5,
    country: "Россия",
    price_retail: 1480,
    price_official: 1690,
    currency: "RUB",
    stock_yanino: 200,
    stock_factory: 500,
    description: "Настенная плитка в голубых тонах из коллекции Mediterranean. Дополняет мозаику этой же коллекции. Глянцевая поверхность усиливает эффект морского бриза.",
    images: ["/images/tiles/mosaic-blue.jpg"],
    main_image: "/images/tiles/mosaic-blue.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: true,
    rating: 4.6,
    reviews_count: 6,
  },

  // ===== DARK ELEGANCE =====
  {
    id: 19,
    sku: "C-DK4S071D",
    name: "Dark Elegance Чёрный 60x60",
    slug: "dark-elegance-chernyj-60x60",
    brand: "Cersanit",
    collection: "Dark Elegance",
    product_type: "Керамогранит",
    format: "60x60",
    surface: "Полированная",
    color: "Чёрный",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Холл"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 2450,
    price_official: 2890,
    currency: "RUB",
    stock_yanino: 60,
    stock_factory: 400,
    description: "Элегантный чёрный керамогранит с полированной поверхностью. Придает интерьеру роскошный и изысканный вид. Подходит для пола в гостиных и холлах.",
    images: ["/images/tiles/black-stone.jpg", "/images/tiles/slate-dark.jpg"],
    main_image: "/images/tiles/black-stone.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: true,
    rating: 4.9,
    reviews_count: 31,
  },
  {
    id: 20,
    sku: "C-DK4S072D",
    name: "Dark Elegance Графит 60x120",
    slug: "dark-elegance-grafit-60x120",
    brand: "Cersanit",
    collection: "Dark Elegance",
    product_type: "Керамогранит",
    format: "60x120",
    surface: "Полированная",
    color: "Чёрный",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Холл", "Кабинет"],
    thickness: "10 мм",
    pieces_per_box: 2,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 3250,
    price_official: null,
    currency: "RUB",
    stock_yanino: 40,
    stock_factory: 250,
    description: "Крупноформатный чёрный керамогранит с полированной поверхностью. Формат 60x120 создает монолитное покрытие с минимумом швов.",
    images: ["/images/tiles/black-stone.jpg"],
    main_image: "/images/tiles/black-stone.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.8,
    reviews_count: 5,
  },
  {
    id: 21,
    sku: "C-DK4S073D",
    name: "Dark Elegance Антрацит 60x60",
    slug: "dark-elegance-antracit-60x60",
    brand: "Cersanit",
    collection: "Dark Elegance",
    product_type: "Керамогранит",
    format: "60x60",
    surface: "Матовая",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Прихожая", "Кухня"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 2150,
    price_official: null,
    currency: "RUB",
    stock_yanino: 100,
    stock_factory: 450,
    description: "Матовый керамогранит из коллекции Dark Elegance в антрацитовом оттенке. Тёмный серый тон с мелкозернистой текстурой натурального камня.",
    images: ["/images/tiles/slate-dark.jpg", "/images/tiles/black-stone.jpg"],
    main_image: "/images/tiles/slate-dark.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.5,
    reviews_count: 10,
  },
  {
    id: 22,
    sku: "C-DK4W074D",
    name: "Dark Elegance Настенная Чёрный 25x75",
    slug: "dark-elegance-nastennaya-chernyj-25x75",
    brand: "Cersanit",
    collection: "Dark Elegance",
    product_type: "Керамическая плитка",
    format: "25x75",
    surface: "Глянцевая",
    color: "Чёрный",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная"],
    thickness: "9 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.5,
    country: "Россия",
    price_retail: 1690,
    price_official: null,
    currency: "RUB",
    stock_yanino: 170,
    stock_factory: 500,
    description: "Чёрная глянцевая настенная плитка. Зеркальный блеск чёрной поверхности создает драматичный эффект в интерьере ванной комнаты.",
    images: ["/images/tiles/black-stone.jpg"],
    main_image: "/images/tiles/black-stone.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.7,
    reviews_count: 12,
  },

  // ===== TERRAZZO ART =====
  {
    id: 23,
    sku: "C-TR4S081D",
    name: "Terrazzo Art Светлый 60x60",
    slug: "terrazzo-art-svetlyj-60x60",
    brand: "Cersanit",
    collection: "Terrazzo Art",
    product_type: "Керамогранит",
    format: "60x60",
    surface: "Матовая",
    color: "Белый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Кухня", "Гостиная", "Прихожая"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 1990,
    price_official: null,
    currency: "RUB",
    stock_yanino: 160,
    stock_factory: 500,
    description: "Керамогранит с дизайном терраццо. Светлая основа с разноцветными каменными вкраплениями. Модный тренд для современных интерьеров. Противоскользящая поверхность R10.",
    images: ["/images/tiles/terrazzo-light.jpg"],
    main_image: "/images/tiles/terrazzo-light.jpg",
    is_new: true,
    is_bestseller: true,
    is_discount: false,
    rating: 4.8,
    reviews_count: 16,
  },
  {
    id: 24,
    sku: "C-TR4S082D",
    name: "Terrazzo Art Серый 60x60",
    slug: "terrazzo-art-seryj-60x60",
    brand: "Cersanit",
    collection: "Terrazzo Art",
    product_type: "Керамогранит",
    format: "60x60",
    surface: "Матовая",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Кухня", "Прихожая"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 1990,
    price_official: 2190,
    currency: "RUB",
    stock_yanino: 120,
    stock_factory: 400,
    description: "Серый терраццо-керамогранит с крупными цветными вкраплениями. Современный и стильный дизайн для кухни и прихожей.",
    images: ["/images/tiles/terrazzo-light.jpg"],
    main_image: "/images/tiles/terrazzo-light.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: true,
    rating: 4.6,
    reviews_count: 9,
  },
  {
    id: 25,
    sku: "C-TR4S083D",
    name: "Terrazzo Art Настенная Светлый 25x75",
    slug: "terrazzo-art-nastennaya-svetlyj-25x75",
    brand: "Cersanit",
    collection: "Terrazzo Art",
    product_type: "Керамическая плитка",
    format: "25x75",
    surface: "Матовая",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная", "Кухня"],
    thickness: "9 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.5,
    country: "Россия",
    price_retail: 1490,
    price_official: null,
    currency: "RUB",
    stock_yanino: 230,
    stock_factory: 600,
    description: "Настенная плитка с модным дизайном терраццо. Светлая основа с мелкими каменными вкраплениями для стен ванной и кухни.",
    images: ["/images/tiles/terrazzo-light.jpg"],
    main_image: "/images/tiles/terrazzo-light.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.5,
    reviews_count: 7,
  },

  // ===== ONYX ROYAL =====
  {
    id: 26,
    sku: "C-ON4S091D",
    name: "Onyx Royal Кремовый 60x120",
    slug: "onyx-royal-kremovyj-60x120",
    brand: "Cersanit",
    collection: "Onyx Royal",
    product_type: "Керамогранит",
    format: "60x120",
    surface: "Полированная",
    color: "Бежевый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Холл", "Спальня"],
    thickness: "10 мм",
    pieces_per_box: 2,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 3490,
    price_official: null,
    currency: "RUB",
    stock_yanino: 50,
    stock_factory: 200,
    description: "Премиальный керамогранит с имитацией оникса. Полупрозрачные прожилки медового оттенка на кремовом фоне. Полированная поверхность для роскошных интерьеров.",
    images: ["/images/tiles/onyx-cream.jpg", "/images/tiles/marble-beige.jpg"],
    main_image: "/images/tiles/onyx-cream.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 5.0,
    reviews_count: 3,
  },
  {
    id: 27,
    sku: "C-ON4S092D",
    name: "Onyx Royal Кремовый 60x60",
    slug: "onyx-royal-kremovyj-60x60",
    brand: "Cersanit",
    collection: "Onyx Royal",
    product_type: "Керамогранит",
    format: "60x60",
    surface: "Полированная",
    color: "Бежевый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Спальня"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 2890,
    price_official: 3190,
    currency: "RUB",
    stock_yanino: 80,
    stock_factory: 300,
    description: "Полированный керамогранит с ониксовым дизайном в формате 60x60. Тёплый кремовый оттенок с благородными прожилками.",
    images: ["/images/tiles/onyx-cream.jpg"],
    main_image: "/images/tiles/onyx-cream.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: true,
    rating: 4.9,
    reviews_count: 11,
  },
  {
    id: 28,
    sku: "C-ON4W093D",
    name: "Onyx Royal Настенная Кремовый 29.7x60",
    slug: "onyx-royal-nastennaya-kremovyj-297x60",
    brand: "Cersanit",
    collection: "Onyx Royal",
    product_type: "Керамическая плитка",
    format: "29.7x60",
    surface: "Глянцевая",
    color: "Бежевый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1790,
    price_official: null,
    currency: "RUB",
    stock_yanino: 140,
    stock_factory: 450,
    description: "Глянцевая настенная плитка с ониксовым рисунком. Создает эффект натурального полудрагоценного камня на стенах ванной комнаты.",
    images: ["/images/tiles/onyx-cream.jpg"],
    main_image: "/images/tiles/onyx-cream.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.7,
    reviews_count: 8,
  },

  // ===== SANDSTONE =====
  {
    id: 29,
    sku: "C-SS4S101D",
    name: "Sandstone Бежевый 60x60",
    slug: "sandstone-bezhevyj-60x60",
    brand: "Cersanit",
    collection: "Sandstone",
    product_type: "Керамогранит",
    format: "60x60",
    surface: "Матовая",
    color: "Бежевый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Кухня", "Прихожая", "Терраса"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 1750,
    price_official: null,
    currency: "RUB",
    stock_yanino: 190,
    stock_factory: 600,
    description: "Керамогранит с текстурой натурального песчаника. Тёплый бежевый оттенок и матовая поверхность R10 для безопасного покрытия пола.",
    images: ["/images/tiles/sandstone-beige.jpg"],
    main_image: "/images/tiles/sandstone-beige.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.6,
    reviews_count: 20,
  },
  {
    id: 30,
    sku: "C-SS4S102D",
    name: "Sandstone Серый 30x60",
    slug: "sandstone-seryj-30x60",
    brand: "Cersanit",
    collection: "Sandstone",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "Матовая",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Прихожая", "Кухня"],
    thickness: "10 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.44,
    country: "Россия",
    price_retail: 1590,
    price_official: 1790,
    currency: "RUB",
    stock_yanino: 210,
    stock_factory: 550,
    description: "Серый керамогранит с текстурой песчаника. Универсальный формат 30x60 для различных схем укладки.",
    images: ["/images/tiles/sandstone-beige.jpg"],
    main_image: "/images/tiles/sandstone-beige.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: true,
    rating: 4.5,
    reviews_count: 14,
  },

  // ===== СТУПЕНИ =====
  {
    id: 31,
    sku: "C-ST2P081D",
    name: "Stone Steps Бежевый 30x60",
    slug: "stone-steps-bezhevyj-30x60",
    brand: "Cersanit",
    collection: "Sandstone",
    product_type: "Ступени",
    format: "30x60",
    surface: "Матовая",
    color: "Бежевый",
    material_type: "Керамогранит",
    application: "Ступени",
    rooms: ["Улица", "Крыльцо"],
    thickness: "12 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.08,
    country: "Россия",
    price_retail: 1980,
    price_official: null,
    currency: "RUB",
    stock_yanino: 180,
    stock_factory: 500,
    description: "Ступени из керамогранита с натуральной каменной текстурой. Матовая противоскользящая поверхность R11 обеспечивает безопасность на улице.",
    images: ["/images/tiles/sandstone-beige.jpg"],
    main_image: "/images/tiles/sandstone-beige.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.4,
    reviews_count: 6,
  },
  {
    id: 32,
    sku: "C-ST2P082D",
    name: "Loft Steps Серый 30x60",
    slug: "loft-steps-seryj-30x60",
    brand: "Cersanit",
    collection: "Loft Brick",
    product_type: "Ступени",
    format: "30x60",
    surface: "Матовая",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Ступени",
    rooms: ["Улица", "Крыльцо"],
    thickness: "12 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.08,
    country: "Россия",
    price_retail: 2100,
    price_official: null,
    currency: "RUB",
    stock_yanino: 120,
    stock_factory: 350,
    description: "Ступени из коллекции Loft Brick. Бетонная текстура в формате ступеней для крыльца и наружных лестниц. Морозостойкий керамогранит R11.",
    images: ["/images/tiles/gray-concrete.jpg"],
    main_image: "/images/tiles/gray-concrete.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.3,
    reviews_count: 4,
  },
]

export const filterOptions = {
  collections: [...new Set(products.map((p) => p.collection))],
  formats: [...new Set(products.map((p) => p.format))],
  colors: [...new Set(products.map((p) => p.color))],
  surfaces: [...new Set(products.map((p) => p.surface))],
  product_types: [...new Set(products.map((p) => p.product_type))],
  applications: [...new Set(products.map((p) => p.application))],
  price_range: {
    min: Math.min(...products.map((p) => p.price_retail)),
    max: Math.max(...products.map((p) => p.price_retail)),
  },
}
