export interface MockProduct {
  id: string
  sku: string
  name: string
  slug: string
  brand: string
  collection: string
  product_type: string
  format: string
  surface: string
  color: string
  material_type: string
  application: string
  rooms: string[]
  thickness: string
  pieces_per_box: number
  sqm_per_box: number
  country: string
  price_retail: number
  price_official: number | null
  currency: string
  stock_yanino: number
  stock_factory: number
  description: string
  images: string[]
  main_image: string
  interior_image: string | null
  is_new: boolean
  is_bestseller: boolean
  is_discount: boolean
  rating: number
  reviews_count: number
}

export interface Category {
  id: string
  name: string
  slug: string
  image: string
  count: number
}

export interface Collection {
  id: string
  name: string
  slug: string
  image: string
  product_count: number
}

export const categories: Category[] = [
  { id: "1", name: "Плитка", slug: "plitka", image: "/images/categories/ceramic.jpg", count: 12 },
  { id: "2", name: "Керамогранит", slug: "keramogranit", image: "/images/categories/porcelain.jpg", count: 24 },
  { id: "3", name: "Мозаика", slug: "mozaika-na-setke", image: "/images/categories/mosaic.jpg", count: 5 },
  { id: "4", name: "Ступень", slug: "stepen", image: "/images/categories/steps.jpg", count: 5 },
]

export const collections: Collection[] = [
  { id: "1", name: "Calacatta", slug: "calacatta", image: "https://pvi.keramogranit-opt.ru/upload/uf/ae8/Calacatta_large_1.jpg", product_count: 5 },
  { id: "2", name: "Wood Concept Natural", slug: "wood-concept-natural", image: "https://pvi.keramogranit-opt.ru/upload/uf/02e/Interior_WN4T013_1.jpg", product_count: 6 },
  { id: "3", name: "Wood Concept Prime", slug: "wood-concept-prime", image: "https://pvi.keramogranit-opt.ru/upload/uf/8e6/Interior_WP4T523_1.jpg", product_count: 3 },
  { id: "4", name: "Wood Concept Rustic", slug: "wood-concept-rustic", image: "https://pvi.keramogranit-opt.ru/upload/uf/581/Interior_WR4T013_1.jpg", product_count: 1 },
  { id: "5", name: "Lofthouse", slug: "lofthouse", image: "https://pvi.keramogranit-opt.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg", product_count: 6 },
  { id: "6", name: "Woodhouse", slug: "woodhouse", image: "https://pvi.keramogranit-opt.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg", product_count: 5 },
  { id: "7", name: "Royal Stone", slug: "royal-stone", image: "https://pvi.keramogranit-opt.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg", product_count: 3 },
  { id: "8", name: "Deco", slug: "deco", image: "https://pvi.keramogranit-opt.ru/upload/uf/b22/DEL232.jpg", product_count: 2 },
  { id: "9", name: "Effecta", slug: "effecta", image: "https://pvi.keramogranit-opt.ru/upload/uf/8b9/INT_Effecta_2_1.jpg", product_count: 2 },
  { id: "10", name: "Galaxy", slug: "galaxy", image: "https://pvi.keramogranit-opt.ru/upload/uf/279/Int_Galaxy_012_1_1.jpg", product_count: 2 },
  { id: "11", name: "Infinity", slug: "infinity", image: "https://pvi.keramogranit-opt.ru/upload/uf/672/INT_Infinity_092_1_1.jpg", product_count: 2 },
  { id: "12", name: "Coliseum", slug: "coliseum", image: "https://pvi.keramogranit-opt.ru/upload/uf/93e/INT_Coliseum_012_2_1.jpg", product_count: 1 },
  { id: "13", name: "Northwood", slug: "northwood", image: "https://pvi.keramogranit-opt.ru/upload/uf/f6c/Northwood_1.jpg", product_count: 1 },
  { id: "14", name: "Amberwood", slug: "amberwood", image: "https://pvi.keramogranit-opt.ru/upload/uf/203/gdn9kz1a0mgtifonj8k82wrukqddv953/A17902_1.jpg", product_count: 4 },
  { id: "15", name: "Carpet", slug: "carpet", image: "https://pvi.keramogranit-opt.ru/upload/uf/5b9/q3u90swubgop0tii237xc669zyi9f2v3/A17930_1.jpg", product_count: 3 },
  { id: "16", name: "Interio", slug: "interio", image: "https://pvi.keramogranit-opt.ru/upload/uf/img/interio.jpg", product_count: 2 },
  { id: "17", name: "Aspen", slug: "aspen", image: "https://pvi.keramogranit-opt.ru/upload/uf/img/aspen.jpg", product_count: 3 },
  { id: "18", name: "Limestone", slug: "limestone", image: "https://pvi.keramogranit-opt.ru/upload/uf/30c/19xpnq19r0fc6eb4qhytzzfyqnxxtqck/17890_1.jpg", product_count: 2 },
  { id: "19", name: "Sandwood", slug: "sandwood", image: "https://pvi.keramogranit-opt.ru/upload/uf/3f7/C_SW4M012D_1a.jpg", product_count: 2 },
  { id: "20", name: "Teakwood", slug: "teakwood", image: "https://pvi.keramogranit-opt.ru/upload/uf/7ae/g1655zkrfweh0vp7qes3x7nwalz9lww2/A17898_1.jpg", product_count: 2 },
  { id: "21", name: "Oakwood", slug: "oakwood", image: "https://pvi.keramogranit-opt.ru/upload/uf/427/4kb9iu72lh9cdv86jxt0vhkf63dz85tt/A17487_01.jpg", product_count: 2 },
  { id: "22", name: "Maplewood", slug: "maplewood", image: "https://pvi.keramogranit-opt.ru/upload/uf/772/MW4M112_1.jpg", product_count: 1 },
  { id: "23", name: "Harbourwood", slug: "harbourwood", image: "https://pvi.keramogranit-opt.ru/upload/uf/b8c/HW4M092D_v1.jpg", product_count: 1 },
  { id: "24", name: "Starwood", slug: "starwood", image: "https://pvi.keramogranit-opt.ru/upload/uf/f48/15934_1.jpg", product_count: 1 },
  { id: "25", name: "Stonehouse", slug: "stonehouse", image: "https://pvi.keramogranit-opt.ru/upload/uf/890/7acdrov6g2g4dhbqf7wcfi1a31sqnn1g/17880_1.jpg", product_count: 1 },
  { id: "26", name: "Coastline", slug: "coastline", image: "https://pvi.keramogranit-opt.ru/upload/uf/1a0/rf4h57fw7lzrsnf8sxb69u62ke8umydm/17894_1.jpg", product_count: 1 },
  { id: "27", name: "Marina", slug: "marina", image: "https://pvi.keramogranit-opt.ru/upload/uf/a85/7hn53k6mpj1km1egfzsd8re4lof0f8c9/A17437_01.jpg", product_count: 1 },
  { id: "28", name: "Desert", slug: "desert", image: "https://pvi.keramogranit-opt.ru/upload/uf/8e1/7hh7bqbgstquhlomqks7frk32vhat9nh/17886_1.jpg", product_count: 1 },
  { id: "29", name: "Artstudio", slug: "artstudio", image: "https://pvi.keramogranit-opt.ru/upload/uf/img/artstudio.jpg", product_count: 1 },
  { id: "30", name: "Slate", slug: "slate", image: "https://pvi.keramogranit-opt.ru/upload/uf/875/C_SF4L402D_1a.jpg", product_count: 1 },
  { id: "31", name: "Ultra", slug: "ultra", image: "https://pvi.keramogranit-opt.ru/upload/uf/fd1/e77qsl58a6lfuvxx7dqdoytsio36kcbz/A17777_1.jpg", product_count: 1 },
  { id: "32", name: "Blend", slug: "blend", image: "https://pvi.keramogranit-opt.ru/files/get/11/21654/29860/800/800/0/", product_count: 1 },
  { id: "33", name: "Tiffany", slug: "tiffany", image: "https://pvi.keramogranit-opt.ru/upload/uf/d90/TV4R052.jpg", product_count: 1 },
  { id: "34", name: "Lina", slug: "lina", image: "https://pvi.keramogranit-opt.ru/upload/uf/1c1/ipi086zb2xksax72oi0j8e67zii7jwcl/A17435_01.jpg", product_count: 1 },
  { id: "35", name: "Luna", slug: "luna", image: "https://pvi.keramogranit-opt.ru/upload/uf/5c4/zcjxbfr0906ddu9edufqdscwj5mx49gn/A17906_1.jpg", product_count: 1 },
  { id: "36", name: "Sonata", slug: "sonata", image: "https://pvi.keramogranit-opt.ru/upload/uf/21a/Sonata-SO4R092D-1.jpg", product_count: 1 },
  { id: "37", name: "Palette", slug: "palette", image: "https://pvi.keramogranit-opt.ru/upload/uf/img/palette.jpg", product_count: 1 },
  { id: "38", name: "Navi", slug: "navi", image: "https://pvi.keramogranit-opt.ru/upload/uf/a99/NV4P092D1.jpg", product_count: 1 },
  { id: "39", name: "Aurora", slug: "aurora", image: "https://pvi.keramogranit-opt.ru/upload/uf/img/aurora.jpg", product_count: 1 },
  { id: "40", name: "Pacific", slug: "pacific", image: "https://pvi.keramogranit-opt.ru/upload/uf/5fb/ejpcf53eitt69mn5dsi2kkc6da5918ks/A17695_01.jpg", product_count: 1 },
  { id: "41", name: "Raven", slug: "raven", image: "https://pvi.keramogranit-opt.ru/upload/uf/366/C_RE4R092D_k1_jpeg.jpg", product_count: 1 },
  { id: "42", name: "Nero", slug: "nero", image: "https://pvi.keramogranit-opt.ru/upload/uf/7f4/7jmj9zj9wfv3mj9pymozir174ukzr96w/A17442_01.jpg", product_count: 1 },
  { id: "43", name: "Space", slug: "space", image: "https://pvi.keramogranit-opt.ru/upload/uf/ba2/SC4L092_1.jpg", product_count: 1 },
  { id: "44", name: "Spark", slug: "spark", image: "https://pvi.keramogranit-opt.ru/upload/uf/799/3l4pix7wmavvhzixpc2qjom4er4mk481/A17785_1.jpg", product_count: 1 },
  { id: "45", name: "Stream", slug: "stream", image: "https://pvi.keramogranit-opt.ru/upload/uf/20f/rbd2zf7fak8vyplzywv2dt22quu8i08f/A17922_01.jpg", product_count: 1 },
  { id: "46", name: "Stilo", slug: "stilo", image: "https://pvi.keramogranit-opt.ru/upload/uf/81d/vx3fgjzvp4xhgasrbpsxh95ar7tm013x/A17433_01.jpg", product_count: 1 },
  { id: "47", name: "Motley", slug: "motley", image: "https://pvi.keramogranit-opt.ru/upload/uf/b8c/l4kowj8fki9wn2v4ghv17xosdq5lcirs/A17924_01.jpg", product_count: 1 },
  { id: "48", name: "Modis", slug: "modis", image: "https://pvi.keramogranit-opt.ru/upload/uf/2b3/hiz8iwu7byw6j0sp5d53lmmg0a3x85yu/17872_1.jpg", product_count: 1 },
  { id: "49", name: "Ritmo", slug: "ritmo", image: "https://pvi.keramogranit-opt.ru/upload/uf/515/o4dzfn6h1vwsoh43mt9ybsfwmuyeubuc/A17912_1.jpg", product_count: 1 },
  { id: "50", name: "Inverno", slug: "inverno", image: "https://pvi.keramogranit-opt.ru/upload/uf/236/w5dg6qmvblrkmw77h5y0ns4ead0phqgl/A17438_01.jpg", product_count: 1 },
  { id: "51", name: "Sherbrooke", slug: "sherbrooke", image: "https://pvi.keramogranit-opt.ru/upload/uf/ea5/q0ryonkjg1j8dm08t6rwjv0qi2xql2n2/A17699_01.jpg", product_count: 1 },
  { id: "52", name: "Mont Blanc", slug: "mont-blanc", image: "https://pvi.keramogranit-opt.ru/files/get/11/21816/29905/800/800/0/", product_count: 1 },
  { id: "53", name: "Grigio Nuovalato", slug: "grigio-nuovalato", image: "https://pvi.keramogranit-opt.ru/upload/uf/36b/d9k1zug73exv5xroxcz2msg6bkl91fnf/A17125_01.jpg", product_count: 1 },
  { id: "54", name: "Siena", slug: "siena", image: "https://pvi.keramogranit-opt.ru/upload/uf/59c/A16008_1.jpg", product_count: 1 },
  { id: "55", name: "Sevilla", slug: "sevilla", image: "https://pvi.keramogranit-opt.ru/upload/uf/975/SE4R053.jpg", product_count: 1 },
  { id: "56", name: "Silvia", slug: "silvia", image: "https://pvi.keramogranit-opt.ru/upload/uf/d04/gyil7wt1cw6qhb0ho0xw5nnd7t7bjwm3/A17431_01.jpg", product_count: 1 },
  { id: "57", name: "Kauri Wood", slug: "kauri-wood", image: "https://pvi.keramogranit-opt.ru/upload/uf/0f1/uy2bye4j6h4ubnrxvfft37785dyf5cl9/17936_1.jpg", product_count: 1 },
  { id: "58", name: "Gold Venice", slug: "gold-venice", image: "https://pvi.keramogranit-opt.ru/upload/uf/0da/uefsnr25qfuu5b7khlor2mmc0oorecum/A17121_01.jpg", product_count: 1 },
  { id: "59", name: "Silver Roots", slug: "silver-roots", image: "https://pvi.keramogranit-opt.ru/upload/uf/17a/9fanhagyx381ocz3t4sgsurwizbvbopc/A17124_01.jpg", product_count: 1 },
  { id: "60", name: "Classy Marble", slug: "classy-marble", image: "https://pvi.keramogranit-opt.ru/upload/uf/626/8nmvabm99q5w4620fssk6y86uzf6to89/A17120_01.jpg", product_count: 1 },
  { id: "61", name: "Residence", slug: "residence", image: "https://pvi.keramogranit-opt.ru/upload/uf/98e/5t69wfryb43mj9cyuf4tn60n410v306u/17874_1.jpg", product_count: 1 },
  { id: "62", name: "Rustico", slug: "rustico", image: "https://pvi.keramogranit-opt.ru/upload/uf/0b3/wsntq57dhzunramfgxppy1w5uc6r3owq/A17429_01.jpg", product_count: 1 },
  { id: "63", name: "Oriental", slug: "oriental", image: "https://pvi.keramogranit-opt.ru/upload/uf/0cc/Oriental-White-OE4R052D-1.jpg", product_count: 1 },
  { id: "64", name: "Loft", slug: "loft", image: "https://pvi.keramogranit-opt.ru/upload/uf/8f3/LO4R452.jpg", product_count: 1 },
  { id: "65", name: "Soft Concrete", slug: "soft-concrete", image: "https://pvi.keramogranit-opt.ru/upload/uf/068/gcqu8u24rft50mgxzpbijnh33k074vg0/A17122_01.jpg", product_count: 1 },
  { id: "66", name: "Sandstone", slug: "sandstone", image: "https://pvi.keramogranit-opt.ru/upload/uf/79e/e4wsrtecqrzgh5aamk00kdpzah0l04a4/17896_1.jpg", product_count: 1 },
  { id: "67", name: "Finwood", slug: "finwood", image: "https://pvi.keramogranit-opt.ru/upload/uf/61e/C_FF4M052D_1a.jpg", product_count: 1 },
  { id: "68", name: "Patinawood", slug: "patinawood", image: "https://pvi.keramogranit-opt.ru/upload/uf/0fb/PT4M112_2.jpg", product_count: 1 },
  { id: "69", name: "Timber Land", slug: "timber-land", image: "https://pvi.keramogranit-opt.ru/upload/uf/0b9/uraopoyg4u5cwva3tqgj26gxxszq0gav/17934_1.jpg", product_count: 1 },
  { id: "70", name: "Greenhouse", slug: "greenhouse", image: "https://pvi.keramogranit-opt.ru/files/get/2/21835/29011/800/800/0/", product_count: 1 },
  { id: "71", name: "Exterio", slug: "exterio", image: "https://pvi.keramogranit-opt.ru/files/get/11/14755/6892/800/800/0/", product_count: 1 },
  { id: "72", name: "Pudra", slug: "pudra", image: "https://pvi.keramogranit-opt.ru/upload/uf/6c7/C_PD4R452D.jpg", product_count: 1 },
  { id: "73", name: "Bonsai Tree", slug: "bonsai-tree", image: "https://pvi.keramogranit-opt.ru/upload/uf/b47/k5vcxzgjn1j9nzf22zuw6icj150cfm9s/17942_1.jpg", product_count: 1 },
  { id: "74", name: "Daisy", slug: "daisy", image: "https://pvi.keramogranit-opt.ru/upload/uf/b2a/A16067.jpg", product_count: 1 },
  { id: "75", name: "Cambio", slug: "cambio", image: "https://pvi.keramogranit-opt.ru/upload/uf/115/evlkpmsosg3p23bttga6aq3mkxvchck8/A17426_01.jpg", product_count: 1 },
  { id: "76", name: "Atria", slug: "atria", image: "https://pvi.keramogranit-opt.ru/upload/uf/d77/Atria_42x42_AN4R012_floor_jpg.jpg", product_count: 1 },
  { id: "77", name: "Landscape", slug: "landscape", image: "https://pvi.keramogranit-opt.ru/files/get/11/21670/30432/800/800/0/", product_count: 1 },
  { id: "78", name: "Ceramill", slug: "ceramill", image: "https://pvi.keramogranit-opt.ru/upload/uf/img/ceramill.jpg", product_count: 1 },
  { id: "79", name: "Chesterwood", slug: "chesterwood", image: "https://pvi.keramogranit-opt.ru/upload/uf/7b6/C_CV4M302D_1.jpg", product_count: 1 },
  { id: "80", name: "Colorwood", slug: "colorwood", image: "https://pvi.keramogranit-opt.ru/upload/uf/343/INT_Colorwood_2_3.jpg", product_count: 1 },
  { id: "81", name: "Concretehouse", slug: "concretehouse", image: "https://pvi.keramogranit-opt.ru/files/get/11/21690/29196/800/800/0/", product_count: 1 },
]

export const mockProducts: MockProduct[] = [
  // ===== CALACATTA =====
  {
    id: "1",
    sku: "KT2L051",
    name: "Calacatta узор белый 29.8x59.8",
    slug: "calacatta-uzor-belyj-298x598",
    brand: "Lincer",
    collection: "Calacatta",
    product_type: "Керамическая плитка",
    format: "29.8x59.8",
    surface: "Глянцевая",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная комната", "Гостиная", "Спальня"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1490,
    price_official: null,
    currency: "RUB",
    stock_yanino: 320,
    stock_factory: 1200,
    description: "Настенная вставка из коллекции Calacatta с изящным узором на белом фоне. Воссоздает утонченную красоту итальянского мрамора Calacatta с характерными серыми и золотистыми прожилками. Идеально подходит для создания элегантного интерьера ванной комнаты, гостиной или спальни.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/d5d/KT2L051.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/b00/Int_Calacatta_2.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/020/Int_Calacatta_3.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/ae8/Calacatta_large_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/d5d/KT2L051.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/ae8/Calacatta_large_1.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.8,
    reviews_count: 34,
  },
  {
    id: "2",
    sku: "KT2L052",
    name: "Calacatta ромбы белый 29.8x59.8",
    slug: "calacatta-romby-belyj-298x598",
    brand: "Lincer",
    collection: "Calacatta",
    product_type: "Керамическая плитка",
    format: "29.8x59.8",
    surface: "Глянцевая",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная комната", "Гостиная", "Спальня"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1550,
    price_official: null,
    currency: "RUB",
    stock_yanino: 250,
    stock_factory: 900,
    description: "Настенная вставка с геометрическим рисунком ромбов на мраморном фоне. Сочетание классического мрамора Calacatta и современной геометрии.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/d53/KT2L052_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/020/Int_Calacatta_3.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/e91/Int_Calacatta_2_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/d53/KT2L052_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/020/Int_Calacatta_3.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.6,
    reviews_count: 18,
  },
  {
    id: "3",
    sku: "KTL052",
    name: "Calacatta белый рельеф 29.8x59.8",
    slug: "calacatta-belyj-relef-298x598",
    brand: "Lincer",
    collection: "Calacatta",
    product_type: "Керамическая плитка",
    format: "29.8x59.8",
    surface: "Рельефная",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная комната", "Гостиная", "Спальня"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1590,
    price_official: 1790,
    currency: "RUB",
    stock_yanino: 180,
    stock_factory: 750,
    description: "Рельефная настенная плитка из коллекции Calacatta. Объемная текстура придает поверхности дополнительную выразительность и глубину, подчеркивая мраморный дизайн.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/c2b/KTL052.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/4c2/INT_Calacatta_2_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/fa4/INT_Calacatta_2_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/c2b/KTL052.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/ae8/Calacatta_large_1.jpg",
    is_new: true,
    is_bestseller: true,
    is_discount: false,
    rating: 4.9,
    reviews_count: 27,
  },
  {
    id: "4",
    sku: "KTL051st",
    name: "Calacatta белый глянцевый 29.8x59.8",
    slug: "calacatta-belyj-glyancevyj-298x598",
    brand: "Lincer",
    collection: "Calacatta",
    product_type: "Керамическая плитка",
    format: "29.8x59.8",
    surface: "Глянцевая",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная комната", "Гостиная", "Спальня"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1450,
    price_official: 1690,
    currency: "RUB",
    stock_yanino: 400,
    stock_factory: 1500,
    description: "Базовая глянцевая плитка из коллекции Calacatta. Классический белый мрамор с серыми прожилками. Универсальная основа для стен ванной комнаты или гостиной.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/77c/KTL051st.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/ae8/Calacatta_large_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/437/Calacatta_large_3.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/77c/KTL051st.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/ae8/Calacatta_large_1.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: true,
    rating: 4.7,
    reviews_count: 42,
  },
  {
    id: "5",
    sku: "A15925",
    name: "Calacatta шеврон белый 29.8x59.8",
    slug: "calacatta-shevron-belyj-298x598",
    brand: "Lincer",
    collection: "Calacatta",
    product_type: "Керамическая плитка",
    format: "29.8x59.8",
    surface: "Глянцевая",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная комната"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1650,
    price_official: null,
    currency: "RUB",
    stock_yanino: 140,
    stock_factory: 500,
    description: "Настенная вставка с рисунком шеврон на мраморном фоне Calacatta. Модный паттерн елочки добавляет динамику и стиль в интерьер ванной.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/3e2/KTL051.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/4c2/INT_Calacatta_2_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/798/INT_Calacatta_2_3.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/3e2/KTL051.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/4c2/INT_Calacatta_2_1.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.7,
    reviews_count: 11,
  },

  // ===== WOOD CONCEPT NATURAL =====
  {
    id: "6",
    sku: "WN4T013",
    name: "Wood Concept Natural бежевый 21.8x89.8",
    slug: "wood-concept-natural-bezhevyj-218x898",
    brand: "Lincer",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "21.8x89.8",
    surface: "Рельефная",
    color: "Бежевый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.18,
    country: "Россия",
    price_retail: 1950,
    price_official: null,
    currency: "RUB",
    stock_yanino: 350,
    stock_factory: 1100,
    description: "Глазурованный керамогранит ректификат из коллекции Wood Concept Natural. Реалистичная имитация натурального бежевого дерева с рельефной поверхностью. Формат 21.8x89.8 создает эффект натуральной доски.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/4af/15971_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/02e/Interior_WN4T013_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/320/Interior_WN4T013_3.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/70f/Interior_WN4T013_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/4af/15971_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/02e/Interior_WN4T013_1.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.9,
    reviews_count: 56,
  },
  {
    id: "7",
    sku: "WN4T103",
    name: "Wood Concept Natural песочный 21.8x89.8",
    slug: "wood-concept-natural-pesochnyj-218x898",
    brand: "Lincer",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "21.8x89.8",
    surface: "Рельефная",
    color: "Песочный",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.18,
    country: "Россия",
    price_retail: 1950,
    price_official: null,
    currency: "RUB",
    stock_yanino: 280,
    stock_factory: 900,
    description: "Керамогранит ректификат с имитацией натурального дерева в теплом песочном оттенке. Рельефная поверхность обеспечивает тактильные ощущения, близкие к натуральному дереву.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/05e/15973_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/2be/Interior_WN4T103_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/045/Interior_WN4T103_3.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/05e/15973_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/2be/Interior_WN4T103_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.8,
    reviews_count: 31,
  },
  {
    id: "8",
    sku: "WN4T113",
    name: "Wood Concept Natural коричневый 21.8x89.8",
    slug: "wood-concept-natural-korichnevyj-218x898",
    brand: "Lincer",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "21.8x89.8",
    surface: "Рельефная",
    color: "Коричневый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Кухня", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.18,
    country: "Россия",
    price_retail: 1950,
    price_official: 2190,
    currency: "RUB",
    stock_yanino: 200,
    stock_factory: 750,
    description: "Классический коричневый керамогранит под дерево. Насыщенный шоколадный оттенок с реалистичной древесной текстурой. Подходит для создания уютного и теплого интерьера.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/01e/15975_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/815/Interior_WN4T113_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/252/Interior_WN4T113_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/01e/15975_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/815/Interior_WN4T113_1.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.7,
    reviews_count: 38,
  },
  {
    id: "9",
    sku: "WN4T303",
    name: "Wood Concept Natural светло-бежевый 21.8x89.8",
    slug: "wood-concept-natural-svetlo-bezhevyj-218x898",
    brand: "Lincer",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "21.8x89.8",
    surface: "Рельефная",
    color: "Светло-бежевый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.18,
    country: "Россия",
    price_retail: 1950,
    price_official: null,
    currency: "RUB",
    stock_yanino: 310,
    stock_factory: 1050,
    description: "Светло-бежевый керамогранит под дерево. Самый нежный и светлый оттенок в линейке Wood Concept Natural. Визуально расширяет пространство.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/9ef/15977_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/3fd/Interior_WN4T303_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/bb9/Interior_WN4T303_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/9ef/15977_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/3fd/Interior_WN4T303_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: true,
    rating: 4.8,
    reviews_count: 24,
  },
  {
    id: "10",
    sku: "A15985",
    name: "Wood Concept Natural темно-коричневый 21.8x89.8",
    slug: "wood-concept-natural-temno-korichnevyj-218x898",
    brand: "Lincer",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "21.8x89.8",
    surface: "Рельефная",
    color: "Темно-коричневый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.18,
    country: "Россия",
    price_retail: 2050,
    price_official: null,
    currency: "RUB",
    stock_yanino: 150,
    stock_factory: 550,
    description: "Темно-коричневый керамогранит под дерево венге. Глубокий благородный оттенок для создания контрастных и стильных интерьеров.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/d0c/15985_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/58c/INT_15985_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/d0f/INT_15985_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/d0c/15985_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/58c/INT_15985_1.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.6,
    reviews_count: 15,
  },
  {
    id: "11",
    sku: "A15987",
    name: "Wood Concept Natural светло-коричневый 21.8x89.8",
    slug: "wood-concept-natural-svetlo-korichnevyj-218x898",
    brand: "Lincer",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "21.8x89.8",
    surface: "Рельефная",
    color: "Светло-коричневый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.18,
    country: "Россия",
    price_retail: 2050,
    price_official: null,
    currency: "RUB",
    stock_yanino: 190,
    stock_factory: 680,
    description: "Светло-коричневый керамогранит с имитацией натуральной древесины. Теплый оттенок карамели создает уютную и комфортную обстановку.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/f5e/15987_10.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/bf9/INT_15987_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/c9f/INT_15987_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/f5e/15987_10.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/bf9/INT_15987_1.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.7,
    reviews_count: 12,
  },

  // ===== WOOD CONCEPT PRIME =====
  {
    id: "12",
    sku: "WP4T093",
    name: "Wood Concept Prime серый 21.8x89.8",
    slug: "wood-concept-prime-seryj-218x898",
    brand: "Lincer",
    collection: "Wood Concept Prime",
    product_type: "Керамогранит",
    format: "21.8x89.8",
    surface: "Рельефная",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Кухня", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.18,
    country: "Россия",
    price_retail: 2150,
    price_official: null,
    currency: "RUB",
    stock_yanino: 170,
    stock_factory: 600,
    description: "Серый керамогранит под дерево из коллекции Wood Concept Prime. Модный серый оттенок выбеленного дуба. Ректифицированные края для минимальных швов.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/0d5/16021_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/295/Interior_WP4T093_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/2e0/Interior_WP4T093_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/0d5/16021_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/295/Interior_WP4T093_1.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.8,
    reviews_count: 29,
  },
  {
    id: "13",
    sku: "WP4T523",
    name: "Wood Concept Prime светло-серый 21.8x89.8",
    slug: "wood-concept-prime-svetlo-seryj-218x898",
    brand: "Lincer",
    collection: "Wood Concept Prime",
    product_type: "Керамогранит",
    format: "21.8x89.8",
    surface: "Рельефная",
    color: "Светло-серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Кухня", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.18,
    country: "Россия",
    price_retail: 2150,
    price_official: 2390,
    currency: "RUB",
    stock_yanino: 240,
    stock_factory: 800,
    description: "Светло-серый керамогранит под дерево. Идеально подходит для скандинавских интерьеров и стиля минимализм. Множество интерьерных решений.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/af4/15981_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/8e6/Interior_WP4T523_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/9df/Interior_WP4T523_2.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/3d5/INT_WP4T523_3_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/af4/15981_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/8e6/Interior_WP4T523_1.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.9,
    reviews_count: 47,
  },
  {
    id: "14",
    sku: "A15989",
    name: "Wood Concept Prime белый 21.8x89.8",
    slug: "wood-concept-prime-belyj-218x898",
    brand: "Lincer",
    collection: "Wood Concept Prime",
    product_type: "Керамогранит",
    format: "21.8x89.8",
    surface: "Рельефная",
    color: "Белый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.18,
    country: "Россия",
    price_retail: 2250,
    price_official: null,
    currency: "RUB",
    stock_yanino: 120,
    stock_factory: 400,
    description: "Белый керамогранит под дерево. Самый светлый оттенок линейки Wood Concept Prime. Создает ощущение простора и свежести в любом помещении.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/99e/15989_10.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/9e4/INT_15989_01.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/644/INT_15989_02.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/99e/15989_10.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/9e4/INT_15989_01.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.8,
    reviews_count: 9,
  },

  // ===== WOOD CONCEPT RUSTIC =====
  {
    id: "15",
    sku: "WR4T013",
    name: "Wood Concept Rustic бежевый 21.8x89.8",
    slug: "wood-concept-rustic-bezhevyj-218x898",
    brand: "Lincer",
    collection: "Wood Concept Rustic",
    product_type: "Керамогранит",
    format: "21.8x89.8",
    surface: "Рельефная",
    color: "Бежевый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 6,
    sqm_per_box: 1.18,
    country: "Россия",
    price_retail: 2050,
    price_official: null,
    currency: "RUB",
    stock_yanino: 200,
    stock_factory: 650,
    description: "Керамогранит с рустикальной текстурой дерева. Выраженный рисунок с сучками и природными дефектами создает живой и аутентичный образ натурального пола.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/039/15983_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/581/Interior_WR4T013_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/67f/Interior_WR4T013_2.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/258/INT_Wood-Concept-Rustic_WR4T013_2_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/039/15983_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/581/Interior_WR4T013_1.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.7,
    reviews_count: 33,
  },

  // ===== LOFTHOUSE =====
  {
    id: "16",
    sku: "LS4O522",
    name: "Lofthouse светло-серый 29.7x59.8",
    slug: "lofthouse-svetlo-seryj-297x598",
    brand: "Lincer",
    collection: "Lofthouse",
    product_type: "Керамогранит",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Светло-серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Спальня", "Кухня"],
    thickness: "10 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.42,
    country: "Россия",
    price_retail: 1650,
    price_official: null,
    currency: "RUB",
    stock_yanino: 300,
    stock_factory: 950,
    description: "Рельефный керамогранит из коллекции Lofthouse в светло-сером оттенке. Текстура натурального камня с индустриальным характером. Идеально для лофт-интерьеров.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/d3c/C_LS4L522D_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/79d/1_32_.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/a8c/3_1_.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/d3c/C_LS4L522D_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/79d/1_32_.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.6,
    reviews_count: 19,
  },
  {
    id: "17",
    sku: "LS4O092",
    name: "Lofthouse серый 29.7x59.8",
    slug: "lofthouse-seryj-297x598",
    brand: "Lincer",
    collection: "Lofthouse",
    product_type: "Керамогранит",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Спальня", "Кухня"],
    thickness: "10 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.42,
    country: "Россия",
    price_retail: 1650,
    price_official: 1890,
    currency: "RUB",
    stock_yanino: 250,
    stock_factory: 800,
    description: "Серый керамогранит с текстурой камня из коллекции Lofthouse. Насыщенный серый тон для создания выразительных интерьеров в стиле лофт и индастриал.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/eef/C_LS4L092D_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/5d0/1_39_.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/3fb/INT_Lofthouse_Mix_2_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/d5b/INT_Lofthouse_Mix_2_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/eef/C_LS4L092D_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/5d0/1_39_.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.7,
    reviews_count: 25,
  },
  {
    id: "18",
    sku: "LS4O096",
    name: "Ступень Lofthouse серый 29.7x59.8",
    slug: "stupen-lofthouse-seryj-297x598",
    brand: "Lincer",
    collection: "Lofthouse",
    product_type: "Ступени",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Лестницы", "Входные группы"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 0.71,
    country: "Россия",
    price_retail: 890,
    price_official: null,
    currency: "RUB",
    stock_yanino: 120,
    stock_factory: 400,
    description: "Ступень из коллекции Lofthouse в сером цвете. Специальный элемент для оформления лестниц, сочетается с базовой плиткой коллекции.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/8c9/LS4O096.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/8c9/LS4O096.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.5,
    reviews_count: 8,
  },
  {
    id: "19",
    sku: "LS4O526",
    name: "Ступень Lofthouse светло-серый 29.7x59.8",
    slug: "stupen-lofthouse-svetlo-seryj-297x598",
    brand: "Lincer",
    collection: "Lofthouse",
    product_type: "Ступени",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Светло-серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Лестницы", "Входные группы"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 0.71,
    country: "Россия",
    price_retail: 890,
    price_official: null,
    currency: "RUB",
    stock_yanino: 95,
    stock_factory: 350,
    description: "Светло-серая ступень из коллекции Lofthouse. Антискользящая поверхность для безопасного оформления лестниц.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/e1d/LS4O526.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/e1d/LS4O526.jpg",
    interior_image: null,
    is_new: false,
    is_bestseller: false,
    is_discount: true,
    rating: 4.4,
    reviews_count: 5,
  },
  {
    id: "20",
    sku: "LS6O096",
    name: "Мозаика Lofthouse серый 28.3x24.6",
    slug: "mozaika-lofthouse-seryj-283x246",
    brand: "Lincer",
    collection: "Lofthouse",
    product_type: "Мозаика",
    format: "28.3x24.6",
    surface: "Матовая",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Стена",
    rooms: ["Ванная комната", "Кухня"],
    thickness: "8 мм",
    pieces_per_box: 10,
    sqm_per_box: 0.7,
    country: "Россия",
    price_retail: 1290,
    price_official: null,
    currency: "RUB",
    stock_yanino: 80,
    stock_factory: 300,
    description: "Мозаика на сетке из коллекции Lofthouse. Серый камень в мозаичном исполнении для стен ванной или кухонного фартука.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/1d7/LS6O096.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/ed3/INT_LOFTHOUSE_5_3.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/1d7/LS6O096.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.6,
    reviews_count: 11,
  },
  {
    id: "21",
    sku: "LS6O526",
    name: "Мозаика Lofthouse светло-серый 28.3x24.6",
    slug: "mozaika-lofthouse-svetlo-seryj-283x246",
    brand: "Lincer",
    collection: "Lofthouse",
    product_type: "Мозаика",
    format: "28.3x24.6",
    surface: "Матовая",
    color: "Светло-серый",
    material_type: "Керамогранит",
    application: "Стена",
    rooms: ["Ванная комната", "Кухня"],
    thickness: "8 мм",
    pieces_per_box: 10,
    sqm_per_box: 0.7,
    country: "Россия",
    price_retail: 1290,
    price_official: null,
    currency: "RUB",
    stock_yanino: 75,
    stock_factory: 280,
    description: "Светло-серая мозаика на сетке из коллекции Lofthouse. Деликатный тон для создания спокойных акцентов.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/e19/LS6O526.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/3c8/2_13_.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/e19/LS6O526.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/3c8/2_13_.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.5,
    reviews_count: 7,
  },

  // ===== WOODHOUSE =====
  {
    id: "22",
    sku: "WS4O116",
    name: "Ступень Woodhouse коричневый 29.7x59.8",
    slug: "stupen-woodhouse-korichnevyj-297x598",
    brand: "Lincer",
    collection: "Woodhouse",
    product_type: "Ступени",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Коричневый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Лестницы", "Входные группы"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 0.71,
    country: "Россия",
    price_retail: 950,
    price_official: null,
    currency: "RUB",
    stock_yanino: 100,
    stock_factory: 380,
    description: "Коричневая ступень из коллекции Woodhouse с имитацией дерева. Антискользящая рельефная поверхность.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/27d/WS4O116.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/27d/WS4O116.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.5,
    reviews_count: 10,
  },
  {
    id: "23",
    sku: "WS4O526",
    name: "Ступень Woodhouse светло-серый 29.7x59.8",
    slug: "stupen-woodhouse-svetlo-seryj-297x598",
    brand: "Lincer",
    collection: "Woodhouse",
    product_type: "Ступени",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Светло-серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Лестницы", "Входные группы"],
    thickness: "10 мм",
    pieces_per_box: 4,
    sqm_per_box: 0.71,
    country: "Россия",
    price_retail: 950,
    price_official: null,
    currency: "RUB",
    stock_yanino: 85,
    stock_factory: 320,
    description: "Светло-серая ступень из коллекции Woodhouse. Сочетание древесной текстуры и светлого тона.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/ae3/WS4O526.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/ae3/WS4O526.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: true,
    rating: 4.4,
    reviews_count: 6,
  },
  {
    id: "24",
    sku: "WS6O116",
    name: "Мозаика Woodhouse коричневый 30x30",
    slug: "mozaika-woodhouse-korichnevyj-30x30",
    brand: "Lincer",
    collection: "Woodhouse",
    product_type: "Мозаика",
    format: "30x30",
    surface: "Матовая",
    color: "Коричневый",
    material_type: "Керамогранит",
    application: "Стена",
    rooms: ["Ванная комната", "Кухня"],
    thickness: "8 мм",
    pieces_per_box: 10,
    sqm_per_box: 0.9,
    country: "Россия",
    price_retail: 1350,
    price_official: null,
    currency: "RUB",
    stock_yanino: 65,
    stock_factory: 250,
    description: "Мозаика на сетке с имитацией дерева. Коричневые оттенки создают теплый акцент на стене.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/e89/WS6O116.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/e89/WS6O116.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.5,
    reviews_count: 8,
  },

  // ===== ROYAL STONE =====
  {
    id: "25",
    sku: "RS2L451",
    name: "Royal Stone мозаика многоцветный 30x30",
    slug: "royal-stone-mozaika-mnogotsvetnyj-30x30",
    brand: "Lincer",
    collection: "Royal Stone",
    product_type: "Мозаика",
    format: "30x30",
    surface: "Глянцевая",
    color: "Многоцветный",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная комната", "Гостиная", "Спальня"],
    thickness: "8 мм",
    pieces_per_box: 12,
    sqm_per_box: 1.08,
    country: "Россия",
    price_retail: 1890,
    price_official: null,
    currency: "RUB",
    stock_yanino: 90,
    stock_factory: 350,
    description: "Многоцветная мозаика на сетке из коллекции Royal Stone. Насыщенные природные оттенки камня создают эффектный акцент на стене.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/084/RS2L451.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/299/INT_Royal_stone_2_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/084/RS2L451.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.7,
    reviews_count: 14,
  },
  {
    id: "26",
    sku: "A16040",
    name: "Royal Stone мозаика белый 30x30",
    slug: "royal-stone-mozaika-belyj-30x30",
    brand: "Lincer",
    collection: "Royal Stone",
    product_type: "Мозаика",
    format: "30x30",
    surface: "Глянцевая",
    color: "Белый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня"],
    thickness: "8 мм",
    pieces_per_box: 12,
    sqm_per_box: 1.08,
    country: "Россия",
    price_retail: 1790,
    price_official: null,
    currency: "RUB",
    stock_yanino: 110,
    stock_factory: 420,
    description: "Белая мозаика из коллекции Royal Stone. Классический белый камень в мозаичном исполнении -- универсальное решение для элегантных интерьеров.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/8df/16040.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/955/INT_Royal_Stone_OR_3_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/104/INT_Royal_Stone_OR_3_3.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/8df/16040.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/955/INT_Royal_Stone_OR_3_1.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.8,
    reviews_count: 6,
  },

  // ===== DECO =====
  {
    id: "27",
    sku: "DE2L381",
    name: "Deco орнамент золотистый 29.8x59.8",
    slug: "deco-ornament-zolotistyj-298x598",
    brand: "Lincer",
    collection: "Deco",
    product_type: "Керамическая плитка",
    format: "29.8x59.8",
    surface: "Глянцевая",
    color: "Золотистый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная комната", "Гостиная", "Спальня"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1690,
    price_official: null,
    currency: "RUB",
    stock_yanino: 140,
    stock_factory: 500,
    description: "Настенная вставка с золотистым орнаментом из коллекции Deco. Утонченный декор для создания акцентной стены в ванной или гостиной.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/028/DE2L381.jpg",
      
      "https://pvi.keramogranit-opt.ru/upload/uf/25b/Deco_Large_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/028/DE2L381.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/b22/DEL232.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.6,
    reviews_count: 16,
  },
  {
    id: "28",
    sku: "DEL232",
    name: "Deco базовая светлая 29.8x59.8",
    slug: "deco-bazovaya-svetlaya-298x598",
    brand: "Lincer",
    collection: "Deco",
    product_type: "Керамическая плитка",
    format: "29.8x59.8",
    surface: "Глянцевая",
    color: "Бежевый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная комната", "Гостиная", "Спальня"],
    thickness: "9 мм",
    pieces_per_box: 10,
    sqm_per_box: 1.78,
    country: "Россия",
    price_retail: 1390,
    price_official: 1590,
    currency: "RUB",
    stock_yanino: 280,
    stock_factory: 900,
    description: "Базовая светлая плитка из коллекции Deco. Нежный бежевый фон -- идеальная основа для сочетания с декоративными вставками коллекции.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/b22/DEL232.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/0f1/Deco_2_Large_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/b22/DEL232.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/b22/DEL232.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: true,
    rating: 4.5,
    reviews_count: 21,
  },

  // ===== EFFECTA =====
  {
    id: "29",
    sku: "EFF-WGA011",
    name: "Effecta бежевый 2.5x60",
    slug: "effecta-bezhevyj-25x60",
    brand: "Lincer",
    collection: "Effecta",
    product_type: "Керамическая плитка",
    format: "2.5x60",
    surface: "Глянцевая",
    color: "Бежевый",
    material_type: "Стекло",
    application: "Стена",
    rooms: ["Ванная комната"],
    thickness: "6 мм",
    pieces_per_box: 20,
    sqm_per_box: 0.3,
    country: "Россия",
    price_retail: 490,
    price_official: null,
    currency: "RUB",
    stock_yanino: 200,
    stock_factory: 700,
    description: "Стеклянный спецэлемент из коллекции Effecta. Тонкая бежева�� полоска для создания изящных линий на стене.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/c45/Effecta_2.5x60_O-EFF-WGA011_decor_jpg.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/8b9/INT_Effecta_2_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/c45/Effecta_2.5x60_O-EFF-WGA011_decor_jpg.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/8b9/INT_Effecta_2_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.3,
    reviews_count: 5,
  },
  {
    id: "30",
    sku: "A15923",
    name: "Effecta панно джунгли бежевый 59.6x59.8",
    slug: "effecta-panno-dzhungli-bezhevyj-596x598",
    brand: "Lincer",
    collection: "Effecta",
    product_type: "Керамическая плитка",
    format: "59.6x59.8",
    surface: "Глянцевая",
    color: "Бежевый",
    material_type: "Керамика",
    application: "Стена",
    rooms: ["Ванная комната"],
    thickness: "9 мм",
    pieces_per_box: 2,
    sqm_per_box: 0.71,
    country: "Россия",
    price_retail: 2490,
    price_official: null,
    currency: "RUB",
    stock_yanino: 50,
    stock_factory: 200,
    description: "Настенное панно с рисунком джунглей из коллекции Effecta. Тропические мотивы на бежевом фоне -- яркий акцент в интерьере ванной комнаты.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/20f/ECL011.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/584/INT_Effecta_jungle_1_1_.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/580/INT_Effecta_jungle_1_3.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/20f/ECL011.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/584/INT_Effecta_jungle_1_1_.jpg",
    is_new: true,
    is_bestseller: false,
    is_discount: false,
    rating: 4.9,
    reviews_count: 3,
  },

  // ===== GALAXY =====
  {
    id: "31",
    sku: "GA4L012",
    name: "Galaxy бежевый 29.7x59.8",
    slug: "galaxy-bezhevyj-297x598",
    brand: "Lincer",
    collection: "Galaxy",
    product_type: "Керамогранит",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Бежевый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Балкон"],
    thickness: "10 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.42,
    country: "Россия",
    price_retail: 1750,
    price_official: null,
    currency: "RUB",
    stock_yanino: 180,
    stock_factory: 650,
    description: "Рельефный керамогранит из коллекции Galaxy в бежевом цвете. Текстура натурального камня с мягкими перепадами тона. Подходит для входных групп и балконов.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/857/GA4L012_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/279/Int_Galaxy_012_1_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/42d/Int_Galaxy_012_2_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/857/GA4L012_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/279/Int_Galaxy_012_1_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.6,
    reviews_count: 13,
  },
  {
    id: "32",
    sku: "GA4L452",
    name: "Galaxy многоцветный 29.7x59.8",
    slug: "galaxy-mnogotsvetnyj-297x598",
    brand: "Lincer",
    collection: "Galaxy",
    product_type: "Керамогранит",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Многоцветный",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Кухня", "Балкон"],
    thickness: "10 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.42,
    country: "Россия",
    price_retail: 1850,
    price_official: null,
    currency: "RUB",
    stock_yanino: 130,
    stock_factory: 480,
    description: "Многоцветный керамогранит из коллекции Galaxy. Игра природных оттенков камня -- от бежевого до серого. Рельефная поверхность с противоскользящим эффектом.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/dbc/GA4L452_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/5bd/Int_Galaxy_452_1_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/188/Int_Galaxy_452_2_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/dbc/GA4L452_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/5bd/Int_Galaxy_452_1_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: true,
    rating: 4.5,
    reviews_count: 10,
  },

  // ===== INFINITY =====
  {
    id: "33",
    sku: "IN4L092",
    name: "Infinity серый 29.7x59.8",
    slug: "infinity-seryj-297x598",
    brand: "Lincer",
    collection: "Infinity",
    product_type: "Керамогранит",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Ванная комната", "Балкон"],
    thickness: "10 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.42,
    country: "Россия",
    price_retail: 1690,
    price_official: null,
    currency: "RUB",
    stock_yanino: 220,
    stock_factory: 750,
    description: "Серый керамогранит с текстурой камня из коллекции Infinity. Универсальный формат 29.7x59.8 для пола в ванной, коридорах и на балконах.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/841/IN4L092_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/672/INT_Infinity_092_1_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/0cb/INT_Infinity_092_2_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/841/IN4L092_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/672/INT_Infinity_092_1_1.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.7,
    reviews_count: 22,
  },
  {
    id: "34",
    sku: "IN4L402",
    name: "Infinity темно-серый 29.7x59.8",
    slug: "infinity-temno-seryj-297x598",
    brand: "Lincer",
    collection: "Infinity",
    product_type: "Керамогранит",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Темно-серый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Гостиная", "Спальня", "Балкон"],
    thickness: "10 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.42,
    country: "Россия",
    price_retail: 1690,
    price_official: 1890,
    currency: "RUB",
    stock_yanino: 160,
    stock_factory: 600,
    description: "Темно-серый керамогранит из коллекции Infinity. Глубокий оттенок камня для создания выразительных контрастных интерьеров.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/782/IN4L402_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/6e7/INT_Infinity_402_1_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/b46/INT_Infinity_402_2_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/782/IN4L402_1.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/6e7/INT_Infinity_402_1_1.jpg",
    is_new: false,
    is_bestseller: false,
    is_discount: false,
    rating: 4.6,
    reviews_count: 17,
  },

  // ===== COLISEUM =====
  {
    id: "35",
    sku: "CO4L012",
    name: "Coliseum бежевый 29.7x59.8",
    slug: "coliseum-bezhevyj-297x598",
    brand: "Lincer",
    collection: "Coliseum",
    product_type: "Керамогранит",
    format: "29.7x59.8",
    surface: "Рельефная",
    color: "Бежевый",
    material_type: "Керамогран��т",
    application: "Пол",
    rooms: ["Гостиная", "Спальня", "Кухня", "Коридор"],
    thickness: "10 мм",
    pieces_per_box: 8,
    sqm_per_box: 1.42,
    country: "Россия",
    price_retail: 1590,
    price_official: null,
    currency: "RUB",
    stock_yanino: 270,
    stock_factory: 900,
    description: "Бежевый керамогранит из коллекции Coliseum с текстурой травертина. Классический камень для элегантных интерьеров гостиных, кухонь и коридоров.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/e34/C_CO4L012D_1f.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/93e/INT_Coliseum_012_2_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/ab6/INT_Coliseum_012_2_2.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/e76/INT_Coliseum_beige_3_2.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/e34/C_CO4L012D_1f.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/93e/INT_Coliseum_012_2_1.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: false,
    rating: 4.8,
    reviews_count: 35,
  },

  // ===== NORTHWOOD =====
  {
    id: "36",
    sku: "NW4M012",
    name: "Northwood бежевый 18.5x59.8",
    slug: "northwood-bezhevyj-185x598",
    brand: "Lincer",
    collection: "Northwood",
    product_type: "Керамогранит",
    format: "18.5x59.8",
    surface: "Матовая",
    color: "Бежевый",
    material_type: "Керамогранит",
    application: "Пол",
    rooms: ["Кухня", "Коридор", "Балкон"],
    thickness: "8 мм",
    pieces_per_box: 9,
    sqm_per_box: 1.0,
    country: "Россия",
    price_retail: 1350,
    price_official: null,
    currency: "RUB",
    stock_yanino: 380,
    stock_factory: 1200,
    description: "Бюджетный керамогранит под дерево из коллекции Northwood. Компактный формат 18.5x59.8 для пола на кухне, в коридорах и на балконах. Матовая поверхность с противоскользящими свойствами.",
    images: [
      "https://pvi.keramogranit-opt.ru/upload/uf/5b6/C_NW4M012D_1a.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/f6c/Northwood_1.jpg",
      "https://pvi.keramogranit-opt.ru/upload/uf/1f6/INT_Northwood_012_2_1.jpg",
    ],
    main_image: "https://pvi.keramogranit-opt.ru/upload/uf/5b6/C_NW4M012D_1a.jpg",
    interior_image: "https://pvi.keramogranit-opt.ru/upload/uf/f6c/Northwood_1.jpg",
    is_new: false,
    is_bestseller: true,
    is_discount: true,
    rating: 4.5,
    reviews_count: 48,
  },
]
